### ISSUE TITLE
Row H216, Col 84 was marked "born that year", but the year before has a 1?

### ISSUE THREAD

**Issue by Edderic** [Edderic/mics-whales#1]
<img width="355" alt="screen shot 2019-02-17 at 7 09 30 am" src="https://user-images.githubusercontent.com/2751152/52912722-27b83900-3283-11e9-89d7-bb053b478603.png">

**Comment by rsullivan-lord** [comment]
I think the yellow hightlight is a mistake here. I've checked another spreadsheet and I don't think we know for sure when that whale was born, but I've asked Christian to double check :)

**Comment by Edderic** [comment]
Oh ok. Thanks, @rsullivan-lord :)

**Comment by rsullivan-lord** [comment]
Christian confirmed - yellow highlight was a mistake, dont know certain age
