### ISSUE TITLE
Does H565, W correspond to a newborn, even though there is no "1" on the yellow square

### ISSUE THREAD

**Issue by Edderic** [Edderic/mics-whales#2]
<img width="984" alt="screen shot 2019-02-17 at 7 25 19 am" src="https://user-images.githubusercontent.com/2751152/52912870-88487580-3285-11e9-86b3-15ec3bcf887d.png">

**Comment by rsullivan-lord** [comment]
No I'm pretty sure that was a mistake left over from highlighting the one above. I also just emailed you a link to a slightly more cleaned up data set. Fixing that error and also highlighting a whale that is known dead and wasn't sighted many times anyway and possibly should be removed?

**Comment by Edderic** [comment]
Ok awesome. I'll use this updated data set. 

The "dead" whale is the orange whale? How do we know that the whale is dead? Because we haven't seen the whale for so long?
