### ISSUE TITLE
Missing years (?) in individual sighting histories

### ISSUE THREAD

**Issue by rsullivan-lord** [Edderic/mics-whales#3]
https://esajournals.onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1002%2Fecs2.1796&file=ecs21796-sup-0001-AppendixS1.pdf

Here's some of the supplemental information from Arso Civil et al., 2017. It shows that to deal with gaps in the sighting histories of individuals they just selected parts of the individuals sighting history that were unbroken - not completely, they assumed like we are that an individual couldn't give birth in consecutive years, so a ? in a year right before or after an observed birth was considered to be a 0 even if the dolphin wasn't sighted that year.

**Comment by Edderic** [comment]
@rsullivan-lord this is great! This clearly shows the approach taken by Arso Civil et al. and that we characterized their work correctly:
1. They only used whales that were observed to have given birth.
2. Like you said, they only took contiguous observed sections for the analysis, discarding sections of unobserved.

Their approach can be improved by taking into account unobserved data, which as we said, would let us make a more representative statement about reproductively active females, not just on experienced mothers which might be more likely to give birth anyway.

One idea I got from reading this is that we could create a simulation to demonstrate the potential bias where looking at "experienced mothers" could be unrepresentative of reproductively-active females

Anyway, I feel like we're on point! 👏 💯 🥇
